blog/urls.py
from django.urls import path
from .views import ProductsView, DetailView, SavedView, ProductUpdate, AboutView, ProductDeleteView, AddProductView, AddCommentView, CommentView, UpdateCommentView, DeleteCommentView, DeleteSavedView


app_name = 'home'
urlpatterns = [
    path('', ProductsView.as_view(), name='home-page'),
    path('detail/<int:pk>/', DetailView.as_view(), name='detail'),
    path('saved/', SavedView.as_view(), name='saved'),
    path('add-save/<int:pk>/', SavedView.as_view(), name='add-save'),
    path('product-update/<int:pk>/', ProductUpdate.as_view(), name='product-update'),
    path('about/', AboutView.as_view(), name='about'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('add-product/', AddProductView.as_view(), name='add-product'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='add-comment'),
    path('comments/<int:pk>/', CommentView.as_view(), name='comment'),
    path('comment-update/<int:pk>/', UpdateCommentView.as_view(), name='comment-update'),
    path('comment-delete/<int:pk>/', DeleteCommentView.as_view(), name='comment-delete'),
    path('delete-saved/<int:pk>/', DeleteSavedView.as_view(), name='delete-saved'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('secret-place/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update-profile/', ProfileUpdateView.as_view(), name='update-profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_image/', blank=True, null=True, default='default_img/user_img.png')

    class Meta:
        db_table = 'custom_user'

    def __str__(self):
        return f"ID: {self.pk} | Username: {self.username}"

users/forms.py
from django import forms
from .models import CustomUser


class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('image', 'first_name', 'last_name', 'email', 'username')

users/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserForm, ProfileUpdateForm
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

from blog.models import Products
# Create your views here.


class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'register.html', context=context)


class LoginView(View):
    def get(self, request):
        create_form = AuthenticationForm()
        context = {
            'form': create_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('home:home-page')
        else:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('home:home-page')


class ProfileView(View):
    def get(self, request):
        products = Products.objects.filter(author=request.user).order_by('-id')
        context = {
            'user': request.user,
            'products': products
        }
        return render(request, 'profile.html', context=context)


class ProfileUpdateView(View):
    def get(self, request):
        update_form = ProfileUpdateForm(instance=request.user)
        context = {
            'form': update_form
        }
        return render(request, 'profile_update.html', context=context)

    def post(self, request):
        update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            return redirect('users:profile')
        else:
            context = {
                'form': update_form
            }
            return render(request, 'profile_update.html', context=context)

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="#">
<title>Login</title>

{% block content %}
<body>
  <h1>Login Page</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
  </form>
</body>
{% endblock content %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}
<title>Profile</title>

<link rel="stylesheet" href="#">

{% block content %}
<body>
  <h1>Profile</h1>
  <img alt="user-image" style="border-radius: 55px" src="{{ user.image.url }} " height="100px"><br>
  <h3>Username: {{ user.username }}</h3>
  <h3>First name: {{ user.first_name }}</h3>
  <h3>Last name: {{ user.last_name }}</h3>
  <h3>Email: {{ user.email }}</h3>
  <a href="{% url 'users:update-profile' %}"><button>Edit profile</button></a><br><br>
  <h4>----------------------------------------------------------------------------------------------------------------------------------------------------</h4>

  <h1>Posts</h1>
  <a href="{% url 'home:add-product' %}"><button>Add Post</button></a><br>
  <h4>----------------------------------------------------------------------------------------------------------------------------------------------------</h4>
  <div>
    {% for product in products %}
      <a href="{% url 'home:detail' product.pk %}"><h4>{{ product.title }}</h4></a>
      {% if product.video %}
      <video width="640" height="480" controls>
      <source src="{{ product.video.url }}" type="video/mp4">
      </video>
    {% else %}
        <a href="{% url 'home:detail' product.pk %}"><img src="{{ product.image.url }}" height="300px"></a>
    {% endif %}
      <h4>----------------------------------------------------------------------------------------------------------------------------------------------------</h4>
    {% endfor %}
  </div>
</body>
{% endblock content %}

users/templates/profile_update.html
{% extends 'base.html' %}
{% load static %}
<title>UpdateProfile</title>

{% block content %}
<link rel="stylesheet" href="{% static 'css/for_proflle_update.css' %}">

<body>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Profile">
  </form>
</body>
{% endblock content %}

users/templates/register.html
{% extends 'base.html' %}
{% load static %}
<title>Register</title>

<link rel="stylesheet" href="{% static 'css/for_register.css' %}">

{% block content %}

<body>
  <h1>Register Page</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
  </form>
</body>
{% endblock content %}