blog/urls.py
from django.urls import path
from .views import ProductsView, DetailView, SavedView, ProductUpdate, AboutView, ProductDeleteView, AddProductView, AddCommentView, CommentView, UpdateCommentView, DeleteCommentView, DeleteSavedView


app_name = 'home'
urlpatterns = [
    path('', ProductsView.as_view(), name='home-page'),
    path('detail/<int:pk>/', DetailView.as_view(), name='detail'),
    path('saved/', SavedView.as_view(), name='saved'),
    path('add-save/<int:pk>/', SavedView.as_view(), name='add-save'),
    path('product-update/<int:pk>/', ProductUpdate.as_view(), name='product-update'),
    path('about/', AboutView.as_view(), name='about'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete'),
    path('add-product/', AddProductView.as_view(), name='add-product'),
    path('add-comment/<int:pk>/', AddCommentView.as_view(), name='add-comment'),
    path('comments/<int:pk>/', CommentView.as_view(), name='comment'),
    path('comment-update/<int:pk>/', UpdateCommentView.as_view(), name='comment-update'),
    path('comment-delete/<int:pk>/', DeleteCommentView.as_view(), name='comment-delete'),
    path('delete-saved/<int:pk>/', DeleteSavedView.as_view(), name='delete-saved'),
]

conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('secret-place/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView


app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update-profile/', ProfileUpdateView.as_view(), name='update-profile'),
]

blog/models.py
from django.db import models
from users.models import CustomUser
# Create your models here.


class Products(models.Model):
    image = models.ImageField(upload_to='all/image', blank=True, null=True, default='default_img/default_product.jpg')
    video = models.FileField(upload_to='all/video', blank=True, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        db_table = 'products'

    def __str__(self):
        return f"ID: {self.pk} | Title: {self.title} | Author: {self.author.username}"


class Comments(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    comment = models.TextField()

    class Meta:
        db_table = 'comments'

    def __str__(self):
        return f"{self.user.username} | Product: {self.product.title}"


class Saved(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)

    class Meta:
        db_table = 'saved'

    def __str__(self):
        return f"ID: {self.pk} | User: {self.user.username} | Product: {self.product.title}"


class About(models.Model):
    image = models.ImageField(upload_to='all/about', blank=True, null=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    title = models.TextField()

    class Meta:
        db_table = 'about_us'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

blog/forms.py
from django.forms import ModelForm
from .models import Saved, Products, Comments


class Addsave(ModelForm):
    class Meta:
        model = Saved
        fields = "__all__"


class ProductUpdateForm(ModelForm):
    class Meta:
        model = Products
        fields = ('image', 'video', 'title', 'description')


class ProductForm(ModelForm):
    class Meta:
        model = Products
        fields = ['image', 'video', 'title', 'description']


class AddCommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['comment']

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import UpdateView, DeleteView

from .models import Products, Saved, About, Comments
from .forms import ProductUpdateForm, AddCommentForm, ProductForm
from django.contrib import messages


# Create your views here.


class AboutView(View):
    def get(self, request):
        about1 = About.objects.all()
        context = {
            'about_us': about1
        }
        return render(request, 'about.html', context=context)


class ProductsView(View):
    def get(self, request):
        products = Products.objects.all().order_by('-id')
        context = {
            'products': products
        }
        return render(request, 'home.html', context=context)


class DetailView(View):
    def get(self, request, pk):
        product = Products.objects.get(pk=pk)
        context = {
            'product': product,

        }
        return render(request, 'detail.html', context=context)


class ProductUpdate(View):
    def get(self, request, pk):
        product = Products.objects.get(pk=pk)
        update_form = ProductUpdateForm(instance=product)
        context = {
            'form': update_form
        }
        return render(request, 'product_update.html', context=context)

    def post(self, request, pk):
        product = Products.objects.get(pk=pk)
        update_form = ProductUpdateForm(request.POST, request.FILES, instance=product)
        if update_form.is_valid():
            update_form.save()
            return redirect('home:detail', pk=pk)
        else:
            context = {
                'form': update_form
            }
            return render(request, 'product_update.html', context=context)


class SavedView(View):
    def get(self, request):
        # Display saved products for the user
        saved_items = Saved.objects.filter(user=request.user).select_related('product').order_by('-id')
        return render(request, 'saved.html', {'saved_items': saved_items})

    def post(self, request, pk):
        product = get_object_or_404(Products, pk=pk)
        if not Saved.objects.filter(product=product, user=request.user).exists():
            Saved.objects.create(product=product, user=request.user)
        return redirect('home:saved')


class DeleteSavedView(View):
    def get(self, request, pk, ):
        saved = get_object_or_404(Saved, pk=pk, user=request.user)
        return render(request, 'delete_saved.html', {'saved': saved})

    def post(self, request, pk):
        saved = get_object_or_404(Saved, pk=pk, user=request.user)
        saved.delete()
        return redirect('home:saved')


class ProductDeleteView(View):
    def get(self, request, pk):
        product = get_object_or_404(Products, pk=pk)
        return render(request, 'delete.html', {'product': product})

    def post(self, request, pk):
        product = get_object_or_404(Products, pk=pk)
        product.delete()
        return redirect('users:profile')


class AddProductView(View):
    def get(self, request):
        form = ProductForm()
        return render(request, 'add_product.html', {'form': form})

    def post(self, request):
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.save()
            return redirect('users:profile')  # Adjust redirect as necessary
        return render(request, 'add_product.html', {'form': form})


class AddCommentView(View):
    def get(self, request, pk):
        product = Products.objects.get(pk=pk)
        if Comments.objects.filter(product=pk, user=request.user).exists():
            messages.error(request, "Siz allaqchon xabar qo'shgansiz!")
            return redirect('home:detail', pk=pk)
        comment_form = AddCommentForm()
        context = {
            'product': product,
            'form': comment_form
        }
        return render(request, 'add_comment.html', context=context)

    def post(self, request, pk):
        product = Products.objects.get(pk=pk)
        if Comments.objects.filter(product=pk, user=request.user).exists():
            messages.error(request, "Siz allaqchon xabar qo'shgansiz!")
            return redirect('home:detail', pk=pk)
        comment_form = AddCommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.product = product
            comment.save()
            messages.success(request, 'Xabar qoshildi')
            return redirect('home:detail', pk=pk)
        else:
            context = {
                'product': product,
                'form': comment_form
            }
            return render(request, 'add_comment.html', context=context)


class CommentView(View):
    def get(self, request, pk):
        product = Products.objects.get(pk=pk)
        comments = Comments.objects.filter(product=pk)
        context = {
            'product': product,
            'comments': comments
        }
        return render(request, 'comments.html', context=context)


class UpdateCommentView(UpdateView):
    model = Comments
    fields = ['comment']
    template_name = "update_comment.html"

    def get_success_url(self):
        return reverse_lazy('home:detail', kwargs={'pk': self.object.product.pk})


class DeleteCommentView(DeleteView):
    model = Comments
    template_name = "delete_comment.html"

    def get_success_url(self):
        return reverse_lazy('home:detail', kwargs={'pk': self.object.product.pk})

blog/templates/about.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% block content %}
<div class="container">
    <h1>About Us</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for about in about_us %}
            {% if about.pk == 1 %}
                <img src="{{ about.image.url }}" height="200px" alt="CEO Image"><br><br>
                <h2>{{ about.first_name }} {{ about.last_name }}</h2>
                <h3>{{ about.title }}</h3>
            {% endif %}
        {% endfor %}
    </form>
</div>
{% endblock content %}

blog/templates/add_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
        }

        h1 {
            color: #333;
            text-align: center;
            margin-top: 50px;
        }

        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
        }

        input[type="submit"] {
            display: block;
            margin: 20px auto 0;
            padding: 10px 20px;
            background-color: #007BFF;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        /* Bu qatordan keyin kelgan CSS kodlar */
    </style>
</head>
<body>
    <h1>{{ books.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Review">
    </form>
</body>
</html>

blog/templates/add_product.html
{% extends 'base.html' %}
{% block content %}
<title>Add Product</title>

<h1>Add New Product</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Product</button>
</form>
{% endblock content %}

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BlogSite</title>
    <link rel="stylesheet" href="{% static 'css/for_base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        header {
            background-color: #fff;
            border-bottom: 1px solid #ccc;
            padding: 20px 0;
            position: fixed;
            width: 100%;
            top: 0;
            z-index: 1000;
        }
        nav {
            display: flex;
            justify-content: space-between;
            align-items: center;
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }
        nav h1, nav h3 {
            margin: 0;
        }
        nav a {
            text-decoration: none;
            color: #333;
            font-size: 18px;
            padding: 0 10px;
        }
        nav a:hover {
            color: #007bff;
        }
        h1 {
            font-size: 24px;
        }
        h3 {
            font-size: 18px;
        }
        .content {
            margin-top: 120px;
            max-width: 800px;
            margin: 120px auto 0;
            padding: 20px;
            background: #fff;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
        footer {
            background-color: #333;
            color: #fff;
            text-align: center;
            padding: 20px 0;
            position: fixed;
            width: 100%;
            bottom: 0;
        }
        footer a {
            color: #fff;
            text-decoration: none;
        }
    </style>
</head>
<body>
<header>
    {% if user.is_authenticated %}
        <nav>
            <a href="{% url 'home:home-page' %}"><h1>Welcome {{ user.username }}!</h1></a>
            <div>
                <a href="{% url 'home:home-page' %}">Home</a>
                <a href="{% url 'home:saved' %}">Saved</a>
                <a href="{% url 'users:profile' %}">Profile</a>
                <a href="{% url 'home:about' %}">About</a>
                <a href="{% url 'users:logout' %}">Logout</a>
            </div>
        </nav>
    {% else %}
        <nav>
            <h1>BlogSite</h1>
            <div>
                <a href="{% url 'home:home-page' %}">Home</a>
                <a href="{% url 'users:register' %}">Register</a>
                <a href="{% url 'users:login' %}">Login</a>
                <a href="{% url 'home:about' %}">About</a>
            </div>
        </nav>
    {% endif %}

    {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

</header>
<div class="content">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

blog/templates/comments.html


{% extends 'base.html' %}
{% block content %}
<body>
    <h3>Comments</h3>
    {% for comment in comments %}
        <p>{{ comment.comment }} | {{ comment.user.username}}</p>
        {% if request.user == comment.user %}
            <p><a href="{% url 'home:comment-update' comment.pk %}">Update</a></p>
            <p><a href="{% url 'home:comment-delete' comment.pk %}">Delete</a></p>
        {% endif %}
    {% endfor %}
    <p><a href="{% url 'home:detail' product.pk %}">Back</a></p>
</body>


{% endblock content %}

blog/templates/delete.html
{% extends 'base.html' %}
{% block content %}

<title>DeleteProduct</title>

<body><br><br><br>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm"><br><br>
  </form>
  <a href="{% url 'home:detail' product.pk %}"><button>No</button></a>
</body>
{% endblock content %}

blog/templates/delete_comment.html
{% extends 'base.html' %}

{% block title %}Delete Review{% endblock %}

{% block content %}
<h2>Are you sure you want to delete this review?</h2>
<form method="post">
  {% csrf_token %}
  <button type="submit">Yes, delete</button>
 <a href="{% url 'home:detail' pk=object.product.pk %}">Cancel</a>
</form>
{% endblock %}

blog/templates/delete_saved.html
{% extends 'base.html' %}

{% block title %}Delete Saved{% endblock %}

{% block content %}
<h2>Are you sure you want to delete this Saved?</h2>
<p>Product: {{ saved.product.title }}</p>
<form action="{% url 'home:delete-saved' saved.pk %}" method="post">
                {% csrf_token %}
                <button type="submit">Confirm Delete</button>
    <a href="{% url 'home:saved' %}">Cancel</a>
</form>
{% endblock %}

blog/templates/detail.html
<title>Product</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <body>
    <h3>Title: {{ product.title }}</h3>
    {% if product.video %}
      <video width="640" height="480" controls>
      <source src="{{ product.video.url }}" type="video/mp4">
      </video>
    {% else %}
        <img src="{{ product.image.url }}" height="300px">
    {% endif %}

    <h4>{{ product.description }}</h4>
    Author: {{ product.author.username }}<br><br>
    {% if user.is_authenticated %}
         <form action="{% url 'home:add-save' product.pk %}" method="post">
             {% csrf_token %}
             <button type="submit">Save Product</button>
         </form>
        {% if user == request.user %}
         <a href="{% url 'home:add-comment' product.pk %}" ><button>Add Comment</button></a>
        {% endif %}
    {% endif %}
    <a href="{% url 'home:comment' product.pk%}"><button>Comments</button></a>

    {% if request.user == product.author %}
      <a href="{% url 'home:product-update' product.pk %}"><button>Edit</button></a>
      <a href="{% url 'home:delete' product.pk %}"><button>Delete</button></a>
    {% endif %}
  </body>
    {% endblock content %}

blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
<body>
    <h1>Today's news</h1>
    {% for product in products %}
        <div>
            <h4>----------------------------------------------------------------------------------------------------------------------------------------------------</h4>
            <a href="{% url 'home:detail' product.pk %}"><h4>{{ product.title }}</h4></a>
            {% if product.video %}
                <video width="640" height="480" controls>
                    <source src="{{ product.video.url }}" type="video/mp4">
                </video>
            {% else %}
                <a href="{% url 'home:detail' product.pk %}"><img src="{{ product.image.url }}" height="300px"></a>
            {% endif %}
        </div>
    {% endfor %}
</body>
{% endblock content %}

blog/templates/product_update.html
<title>UpdateProduct</title>

{% extends 'base.html' %}
{% block content %}
<link rel="stylesheet" href="">
<header>
  <a href="{% url 'home:home-page' %}">Home</a>
</header>

<body>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
</body>
{% endblock content %}

blog/templates/saved.html
{% extends 'base.html' %}
{% block content %}
<body>
    {% if saved_items %}
        {% for i in saved_items %}
            <h3>-------------------------------------------------------------------------------------------------------------------------------------</h3>
            <a href="{% url 'home:detail' i.product.pk %}"><h4>{{ i.product.title }}</h4></a>
            {% if i.product.video %}
                <video width="640" height="480" controls>
                    <source src="{{ product.video.url }}" type="video/mp4">
                </video>
                <a href="{% url 'home:delete-saved' i.pk %}">Delete</a>
            {% else %}
                <a href="{% url 'home:detail' i.product.pk %}"><img src="{{ i.product.image.url }}" height="300px"></a>
                <a href="{% url 'home:delete-saved' i.pk %}">Delete</a>
            {% endif %}
        {% endfor %}
    {% else %}
        <h2>No contents saved yet.</h2>
    {% endif %}
</body>


{% endblock content %}

blog/templates/update_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
        }

        form {
            max-width: 400px;
            margin: 50px auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
        }

        input[type="text"],
        input[type="email"],
        textarea {
            width: 100%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            width: 100%;
            padding: 10px;
            background-color: #007BFF;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>